# Generated by Django 3.1.1 on 2021-08-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdsdata',
            name='file_name',
            field=models.TextField(blank=True),
        ),
    ]
