# Generated by Django 3.1.1 on 2021-09-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tdsdata_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_type', models.TextField()),
                ('position_data', models.TextField(blank=True)),
                ('intensity_data', models.TextField(blank=True)),
            ],
        ),
    ]
