# Generated by Django 4.0 on 2022-02-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220215_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdsdata',
            name='measure_type',
            field=models.CharField(default='RAPID', max_length=10),
        ),
        migrations.AddField(
            model_name='tdsdata',
            name='measuring_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tdsdata',
            name='sampling_rate',
            field=models.FloatField(null=True),
        ),
    ]
